declare module 'virtual:ox-content/collections' {
	import type { CollectionEntry, CollectionQueryBuilder } from '@ox-content/vite-plugin';

	/** Queries the collection manifest generated by the Ox Content Vite plugin. */
	export function queryCollection<T extends CollectionEntry = CollectionEntry>(
		name: string,
	): CollectionQueryBuilder<T>;
}
declare module 'virtual:site/ssr-styles' {
	const styles: { sharedStyles: string[]; pageStyles: Record<string, string[]> };
	export default styles;
}
