minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - gray-matter-es

overrides:
  sharp: ^0.34.5

patchedDependencies:
  markdown-it-image-figures: patches/markdown-it-image-figures.patch
  markdown-it-link-preview: patches/markdown-it-link-preview.patch

onlyBuiltDependencies:
  - core-js
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
  - workerd

shellEmulator: true
