minimumReleaseAge: 1440

overrides:
  sharp: ^0.34.5

patchedDependencies:
  markdown-it-link-preview: patches/markdown-it-link-preview.patch

onlyBuiltDependencies:
  - core-js
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
  - workerd

shellEmulator: true
