minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - gray-matter-es

overrides:
  sharp: ^0.34.5

patchedDependencies:
  markdown-it-image-figures: patches/markdown-it-image-figures.patch
  markdown-it-link-preview: patches/markdown-it-link-preview.patch

shellEmulator: true

# Security settings (supply chain attack prevention)
# See: https://pnpm.io/settings

# Blocks lifecycle scripts (postinstall, etc.) from running in dependencies by default
# Only packages listed in allowBuilds can run build scripts
# Prevents Shai-Hulud-style worm attacks that exploit automatic script execution
strictDepBuilds: true

# true: allow build scripts, false: block build scripts
allowBuilds:
  core-js: true
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
  workerd: true

# Blocks dependencies from non-registry sources (Git repos, tarball URLs)
# Prevents PhantomRaven-style attacks that bypass npm scanning
blockExoticSubdeps: true

# Prevents trust level downgrades between package versions
# Blocks installations when publisher credentials downgrade from GitHub OIDC to basic auth
trustPolicy: no-downgrade
