[default]
locale = 'en-gb'
extend-ignore-re = [
	"(?s)(#|//)\\s*spellchecker:off[\\s\\S]*?(#|//)\\s*spellchecker:on",
	"(?s)<!--\\s*spellchecker:off\\s*-->[\\s\\S]*?<!--\\s*spellchecker:on\\s*-->",
	"(?s)/\\*\\s*spellchecker:off\\s*\\*/[\\s\\S]*?/\\*\\s*spellchecker:on\\s*\\*/",
	"(?Rm)^.*#\\s*spellchecker:disable-line$",
	"(?m)^.*<!--\\s*spellchecker:disable-line\\s*-->\\n.*$",
]

[default.extend-words]
Artifact = "Artifact"
Edn = "Edn"
IHS = "IHS"
Organization = "Organization"
behavior = "behavior"
capitalize = "capitalize"
catalog = "catalog"
center = "center"
color = "color"
items-center = "items-center"
justify-center = "justify-center"
normalized = "normalized"
optimize = "optimize"
serialize = "serialize"
serialized = "serialized"

[files]
extend-exclude = [
	"node_modules/**",
	"**/*.json",
	# Migrated Zenn blog posts
	"**/*-zenn-*/**",
]
