name: 'Build Setup'
description: 'Setup node, pnpm, and turbo cache'
inputs:
  pnpm-version:
    description: 'pnpm version'
    required: true
    default: '8'
  node_module_cache_name:
    description: 'node_module_cache_name'
    required: false
    default: '1'
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        cache: 'pnpm'

    - name: Launch Turbo Remote Cache Server
      uses: dtinth/setup-github-actions-caching-for-turbo@v1.1.0

    - name: cache node_modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ inputs.node_module_cache_name }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install node_modules
      run: pnpm i
      shell: bash
