name: Setup Nix
description: Install Nix and load the development environment
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      with:
        github_access_token: ${{ github.token }}

    - name: Load Nix development environment
      shell: bash
      run: nix develop --command true
