// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const CheckButton: typeof import("./components/CheckButton.svelte")["default"]
    const GitHubNav: typeof import("./components/GitHubNav.svelte")["default"]
    const HeadTitle: typeof import("./components/HeadTitle.svelte")["default"]
    const Image: typeof import("./components/Image.svelte")["default"]
    const LargeTitle: typeof import("./components/LargeTitle.svelte")["default"]
    const ListView: typeof import("./components/ListView.svelte")["default"]
    const Nav: typeof import("./components/Nav.svelte")["default"]
    const OssProjectCard: typeof import("./components/OssProjectCard.svelte")["default"]
    const Profile: typeof import("./components/Profile.svelte")["default"]
    const ProjectTitle: typeof import("./components/ProjectTitle.svelte")["default"]
    const ShowcaseCard: typeof import("./components/ShowcaseCard.svelte")["default"]
    const Social: typeof import("./components/Social.svelte")["default"]
}

export {}
