declare module 'virtual:ox-content/collections' {
	import type { CollectionQueryBuilder } from '@ox-content/vite-plugin';

	/** Queries the collection manifest generated by the Ox Content Vite plugin. */
	export function queryCollection(name: string): CollectionQueryBuilder;
}
