name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - parallel:
          - name: Run Gitleaks
            run: gitleaks detect --source . --config .gitleaks.toml
          - name: Run Typo Check
            run: pnpm run typos
          - name: Run Vite+ Check
            run: pnpm run check
          - name: Run Tests
            run: pnpm run test
          - name: Validate Content
            run: pnpm run validate:content
