on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build hook
        run: |
          curl -X POST ${{ secrets.BUILD_HOOK_URL }}
